[packages]
#
brew = [
    "wget",
    "pipx",
    "tree",
    "lsd",
    "tldr", # dev docs and manuals, e.g. `tldr uv`
    "node",
    "autojump",
    "fzf",
    "rust",
    "uv",
    "pip-tools",
    "terminal-notifier",
]

cask = [
    "google-chrome",
    "devtoys",
    "iterm2",
    "jetbrains-toolbox",
    "pycharm",
    "webstorm",
    "slack",
    "github",
    "bettermouse", # config: config/app_settings/bettermouse_config.plist
    "zoom",
    "postman",
    "rectangle",
    "zed",
    "chatgpt",
    "onedrive",
    "notion",
    "codex-app",
]
